---
- name: Stop containers before Systemd activation
  become: false
  containers.podman.podman_container:
    name: "{{ item }}"
    state: stopped
  loop:
    - vaultwarden
    - vaultwarden-backup
    - rsshub-app
    - gatus
    - letterboxd-app
    - caddy

- name: Reload daemon
  become: false
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true

- name: Enable containers autostart via systemd
  become: false
  ansible.builtin.systemd:
    name: "container-{{ item }}"
    scope: user
    enabled: true
    state: started
  loop:
    - vaultwarden
    - vaultwarden-backup
    - rsshub-app
    - gatus
    - letterboxd-app
    - caddy
