---
- name: Create data folder
  become: false
  ansible.builtin.file:
    path: "{{ vaultwarden_dir }}"
    state: directory
    mode: '0755'

- name: Setup Vaultwarden
  become: false
  containers.podman.podman_container:
    name: vaultwarden
    image: docker.io/vaultwarden/server:latest
    network: "{{ proxy_network }}"
    state: started
    restart_policy: always
    volumes:
      - "{{ vaultwarden_dir }}:/data:Z"
    env:
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      DOMAIN: "https://{{ vaultwarden_domain }}"
    generate_systemd:
      path: "/home/{{ ansible_user }}/.config/systemd/user/"
      restart_policy: always
      names: true
