---
- name: Fail2ban installation
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Setup local config (jail.local)
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    mode: "0644"
    content: |
      [DEFAULT]
      bantime  = 1h
      findtime = 10m
      maxretry = 5

      [sshd]
      enabled = true
      port    = ssh
      logpath = /var/log/auth.log
      backend = %(sshd_backend)s

- name: Enable and start Fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Restart Fail2ban if config was changed
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
