---
- name: Create data folder
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  loop:
    - "{{ vaultwarden_backup_dir }}"
    - "{{ vaultwarden_backup_dir }}/backups"
    - "{{ vaultwarden_backup_dir }}/logs"

- name: Setup Vaultwarden Backup
  become: false
  containers.podman.podman_container:
    name: vaultwarden-backup
    image: docker.io/bruceforce/vaultwarden-backup:latest
    network: "{{ proxy_network }}"
    state: created
    restart_policy: always
    volumes:
      - "{{ vaultwarden_dir }}:/data:Z"
      - "{{ vaultwarden_backup_dir }}/backups:/backups:Z"
      - "{{ vaultwarden_backup_dir }}/logs:/logs:Z"
    env:
      UID: 1001
      GID: 1001
      BACKUP_DIR: "/backups/"
      LOG_DIR: "/logs/"
      LOG_LEVEL: INFO
      CRON_TIME: "0 5 * * *" # EVERY DAY @ 5am
      DELETE_AFTER: 30
      TIMESTAMP: true
      BACKUP_ADD_DATABASE: true
      BACKUP_ADD_ATTACHMENTS: true
      BACKUP_ADD_CONFIG_JSON: true
      BACKUP_ADD_ICON_CACHE: true
      BACKUP_ADD_RSA_KEY: true
    generate_systemd:
      path: "/home/{{ ansible_user }}/.config/systemd/user/"
      restart_policy: always
      names: true
