---
- name: Setup Vaultwarden Backup
  become: false
  containers.podman.podman_container:
    name: vaultwarden-backup
    image: docker.io/ttionya/vaultwarden-backup:latest
    network: "{{ proxy_network }}"
    state: created
    restart_policy: always
    volumes:
      - "{{ vaultwarden_dir }}:/data:ro"
    env:
      DATA_DIR: "/data"
      CRON_TIME: "0 3 * * *" # Every day at 03:00
      BACKUP_KEEP_DAYS: "30"   # Keep backups for the last 30 days
      RCLONE_REMOTE_TYPE: "s3"
      RCLONE_CONFIG_S3_PROVIDER: "Other"
      RCLONE_CONFIG_S3_ACCESS_KEY_ID: "{{ vault_b2_key_id }}"
      RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "{{ vault_b2_app_key }}"
      RCLONE_CONFIG_S3_ENDPOINT: "{{ vault_b2_endpoint }}"
      RCLONE_CONFIG_S3_REGION: "eu-central-003"
      RCLONE_REMOTE_PATH: "{{ vaultwarden_backup_destination }}/vaultwarden-backups"
      ZIP_ENABLE: true
      ZIP_TYPE: "zip"
      ZIP_PASSWORD: "{{ vault_vaultwarden_backup_zip_password }}" # Additional encryption
    generate_systemd:
      path: "/home/{{ ansible_user }}/.config/systemd/user/"
      restart_policy: always
      names: true
